[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@lib/=lib",
    "@test/=test"
]

fuzz_runs = 1000

# Keep other settings
[profile.ci]
verbosity = 4

gas_reports = ["noirai"]

[dependencies]
forge-std = "1.9.6"
solady = "0.1.9"

[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_version = false


[etherscan]
sonic = { key = "${ETHERSCAN_API_KEY}", url = "https://api.sonicscan.org/api" }

[profile.default.fuzz]
runs = 1000

[profile.default.rpc_endpoints]
sonic = "${SONIC_RPC_URL}"

[profile.default.etherscan]
sonic = { key = "${ETHERSCAN_API_KEY}" }

