[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
optimizer = true
optimizer_runs = 200
solc = "0.8.26"

remappings = [
    "@lib/=lib",
    "@test/=test"
]

fuzz_runs = 1000

# Keep other settings
[profile.ci]
verbosity = 4

gas_reports = ["noirai"]

[dependencies]
forge-std = "1.9.6"
solady = "0.1.9"

[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_version = false


[etherscan]
146 = { key = "${ETHERSCAN_API_KEY}", url = "https://api.sonicscan.org/api" }


[profile.default.fuzz]
runs = 1000

[profile.default.rpc_endpoints]
146 = "${SONIC_RPC_URL}"
